# Generated by Django 5.0.1 on 2024-01-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateogory',
            new_name='category',
        ),
    ]
