# Generated by Django 5.0.1 on 2024-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_post_file_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
